experiment:
    id: train_sloper4d_no_map_fm
##Data
data:
    data_dir: /home/sgalaaou/workspace/SLOPER4D/per_person_updated.pkl
    dataloader: 'sloper4d'
    points_per_object: -1
    align_objects: True
    stacking_type: max
    normalize_points: False

##Training
train:
    uncond_prob: 0.1
    uncond_w: 1.
    n_gpus: 4
    num_workers: 16
    max_epoch: 200
    lr: 0.0001
    batch_size: 32
    decay_lr: 1.0e-4
    class_conditional: False
    ema: True

# Flow Matching hyperparameters
flow:
    t_steps: 1000  # Not actively used but kept for compatibility
    s_steps: 50    # Number of ODE integration steps during sampling
    ode_solver: euler  # 'euler' or 'rk4' (4th order Runge-Kutta, more accurate but slower)
    reg_weight: 0.0  # Regularization weight on mean and std of velocity predictions
    visualize: False

##Network
model:
    embeddings: pointnet
    num_conditions: 85 #76
    cyclic_conditions: 73
    linear_conditions: 10
    map_shape_to_one: False
    relative_angles: False
    num_classes: 1
    size: DiT-XS/4
    conditioning: logen
    pretrained: False # unused
    improved_cfg: True # unused
    in_channels: 3
